name: test-fwupd-sample
version: '1.0'
summary: A sample snap to install newer firmware updates over fwupd
description: |
  This snap gives a sample to demostrate how the client updates
  firmware through fwupd for reference implementation.
architectures:
- amd64
confinement: strict
base: core18
grade: stable

plugs:
  fwupd-data:
    content: fwupd-data
    interface: content
    target: $SNAP_DATA
  fwupd-plug:
    interface: fwupd
    
slots:
  fwupd-slot:
    interface: fwupd

apps:
  firmwareupgrade:
    command: bin/firmware_upgrade
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0/
      G_MESSAGES_DEBUG: all
      G_DEBUG: all
      G_MESSAGES_PREFIXED: all
    plugs:
      - network
      - fwupd-plug
    slots:
      - fwupd-slot

parts:
  firmwareupgrade:
    plugin: python
    source: .
    python-version: python3
    stage-packages:
      - python3-wget
      - libgirepository1.0-dev
      - python3-gi
      - gir1.2-fwupd-2.0
